# Generated by Django 5.2 on 2025-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='img/logo.png', help_text='Upload the site logo (recommended size: 50px height)', upload_to='logos/')),
                ('twitter_url', models.URLField(blank=True, default='#', help_text='Twitter profile URL')),
                ('facebook_url', models.URLField(blank=True, default='#', help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, default='#', help_text='Instagram profile URL')),
                ('login_url', models.URLField(blank=True, default='#', help_text='Login page URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header Setting',
                'verbose_name_plural': 'Header Settings',
            },
        ),
    ]
