# Generated by Django 5.2 on 2025-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgtn_pmts_text', models.CharField(default='CGTN PMTS', help_text='Text for CGTN PMTS logo/link', max_length=50)),
                ('about_text', models.TextField(default='The PMTS provides comprehensive information on all county projects, including project descriptions, status updates, timelines, budgets, progress reports, and relevant documentation.', help_text='About section description')),
                ('financial_years', models.JSONField(blank=True, default=list, help_text="List of financial years (e.g., [{'text': 'Public Dashboard', 'url': '#'}])")),
                ('important_links', models.JSONField(blank=True, default=list, help_text="List of important links (e.g., [{'text': 'FAQs', 'url': '#'}])")),
                ('contact_phone', models.CharField(default='254720031035', help_text='Contact phone number', max_length=20)),
                ('contact_email', models.EmailField(default='info@transnzoia.go.ke', help_text='Contact email', max_length=254)),
                ('contact_address', models.CharField(default='P.O BOX 1683 Kitale', help_text='Contact address', max_length=100)),
                ('twitter_url', models.URLField(blank=True, default='#', help_text='Twitter profile URL')),
                ('facebook_url', models.URLField(blank=True, default='#', help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, default='#', help_text='Instagram profile URL')),
                ('copyright_year', models.CharField(default='2025', help_text='Copyright year', max_length=4)),
                ('copyright_text', models.CharField(default='COUNTY GOVERNMENT OF TRANS-NZOIA | ALL RIGHTS RESERVED.', help_text='Copyright text', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
