# Generated by Django 5.2 on 2025-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_footersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='important_links',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_links',
            field=models.JSONField(blank=True, default=list, help_text="List of quick links (e.g., [{'text': 'FAQs', 'url': '/faqs/'}])"),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='financial_years',
            field=models.JSONField(blank=True, default=list, help_text="List of financial years (e.g., [{'text': 'FY 2022-2023', 'url': '/fy/2022-2023/'}])"),
        ),
    ]
