# Generated by Django 5.2 on 2025-04-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_footersettings_important_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_content', models.JSONField(default=dict, help_text='Content for About page (mission, vision, objectives, etc.)')),
                ('faqs_content', models.JSONField(default=list, help_text='List of FAQs (question and answer pairs)')),
                ('contact_content', models.JSONField(default=dict, help_text='Contact page details (departments, general info)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={},
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='cgtn_pmts_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='financial_years',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='quick_links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='login_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
