# Generated by Django 5.2 on 2025-04-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_pagesettings_alter_footersettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name': 'Footer settings', 'verbose_name_plural': 'Footer settings'},
        ),
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'Header settings', 'verbose_name_plural': 'Header settings'},
        ),
        migrations.AlterModelOptions(
            name='pagesettings',
            options={'verbose_name': 'Page settings', 'verbose_name_plural': 'Page settings'},
        ),
    ]
