# Generated by Django 5.2 on 2025-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_footersettings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagesettings',
            name='contact_content',
        ),
        migrations.RemoveField(
            model_name='pagesettings',
            name='faqs_content',
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='contact_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='contact_departments',
            field=models.JSONField(default=list, help_text='List of departments with name and emails'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='contact_office_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='core_values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='faqs',
            field=models.JSONField(default=list, help_text='List of FAQs with question and answer'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='intro_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='intro_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='objectives',
            field=models.JSONField(default=list, help_text='List of objectives with title, description, icon'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='about_content',
            field=models.TextField(blank=True, help_text='General content for About page'),
        ),
    ]
