# Generated by Django 5.1.7 on 2025-03-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectprogressphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeedback',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Extremely Dissatisfied')]),
        ),
    ]
