# Generated by Django 5.1.7 on 2025-03-29 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('projects', '0003_alter_projectfeedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfeedback',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='flagged_inappropriate',
            field=models.BooleanField(default=False, help_text='Marked as potentially inappropriate by system/moderator.'),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='id_number',
            field=models.CharField(default=1, help_text='Your National ID number.', max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid ID number.', regex='^[0-9]{7,8}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='phone',
            field=models.CharField(blank=True, help_text='(Optional) Your phone number.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='reported_inappropriate',
            field=models.BooleanField(default=False, help_text='Reported as inappropriate by a user.'),
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='sub_county',
            field=models.ForeignKey(default=1, help_text='Select your Sub-County.', on_delete=django.db.models.deletion.PROTECT, to='locations.subcounty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfeedback',
            name='ward',
            field=models.ForeignKey(default=1, help_text='Select your Ward.', on_delete=django.db.models.deletion.PROTECT, to='locations.ward'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectfeedback',
            name='comment',
            field=models.TextField(help_text='Your feedback or comment about the project.'),
        ),
        migrations.AlterField(
            model_name='projectfeedback',
            name='email',
            field=models.EmailField(blank=True, help_text='(Optional) Your email address.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='projectfeedback',
            name='name',
            field=models.CharField(help_text='Your full name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectfeedback',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Very Satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Dissatisfied'), (1, 'Extremely Dissatisfied')], default=3, help_text='Rate your satisfaction with the project.'),
        ),
    ]
