# Generated by Django 5.1.7 on 2025-04-13 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_staffreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback_attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optional description of the attachment.', max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_image', models.BooleanField(default=False, help_text='Is this attachment an image?')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.projectfeedback')),
            ],
            options={
                'verbose_name': 'Feedback Attachment',
                'verbose_name_plural': 'Feedback Attachments',
                'ordering': ['-upload_date'],
            },
        ),
    ]
