# Generated by Django 5.1.7 on 2025-04-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectfeedbackattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReplyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_image', models.BooleanField(default=False, help_text='Is this attachment an image?')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.staffreply')),
            ],
            options={
                'verbose_name': 'Staff Reply Attachment',
                'verbose_name_plural': 'Staff Reply Attachments',
                'ordering': ['-upload_date'],
            },
        ),
    ]
