# Generated by Django 5.1.7 on 2025-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_staffreplyattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor_address',
            field=models.TextField(blank=True, help_text='(Optional) Contractor office address.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_email',
            field=models.EmailField(blank=True, help_text='(Optional) Contractor email address.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_phone',
            field=models.CharField(blank=True, help_text='(Optional) Contractor phone number.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_flagship',
            field=models.BooleanField(default=False, help_text='Is this a flagship project?'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('capital', 'Capital'), ('non_capital', 'Non-Capital')], default='capital', max_length=20),
        ),
    ]
