# Generated by Django 5.1.7 on 2025-04-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_contractor_address_project_contractor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contractor_address',
            field=models.TextField(blank=True, help_text='Contractor office address.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor_email',
            field=models.EmailField(blank=True, help_text='Contractor email address.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contractor_phone',
            field=models.CharField(blank=True, help_text='Contractor phone number.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementing_agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
