- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - python3-pip
      - python3-dev
      - python3-venv
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - nginx
      - git
      - supervisor
      - python3-psycopg2
    state: present

- name: Check if app user exists
  ansible.builtin.command: "id {{ app_user }}"
  register: user_check
  changed_when: false
  failed_when: false # Don't fail if user doesn't exist (rc=1)

- name: Create app user if it does not exist
  ansible.builtin.user:
    name: "{{ app_user }}"
    shell: /bin/bash
    home: "{{ app_home }}"
    state: present
  when: user_check.rc != 0

- name: Create app directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
  with_items:
    - "{{ app_src_dir }}"
    - "{{ app_logs_dir }}"
