# Generated by Django 5.1.7 on 2025-04-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgtn_pmts_text', models.TextField(blank=True)),
                ('about_text', models.TextField(blank=True)),
                ('financial_years', models.JSONField(default=list)),
                ('quick_links', models.JSONField(default=list)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.TextField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('copyright_year', models.CharField(blank=True, max_length=4)),
                ('copyright_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer settings',
                'verbose_name_plural': 'Footer settings',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('login_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header settings',
                'verbose_name_plural': 'Header settings',
            },
        ),
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_content', models.TextField(blank=True, help_text='General content for About page')),
                ('intro_title', models.CharField(blank=True, max_length=200)),
                ('intro_description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('core_values', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list, help_text='List of objectives with title, description, icon')),
                ('faqs', models.JSONField(default=list, help_text='List of FAQs with question and answer')),
                ('contact_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_office_hours', models.CharField(blank=True, max_length=200)),
                ('contact_departments', models.JSONField(default=list, help_text='List of departments with name and emails')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page settings',
                'verbose_name_plural': 'Page settings',
            },
        ),
    ]
