# Generated by Django 5.1.7 on 2025-04-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesettings',
            name='additional_features',
            field=models.JSONField(default=list, help_text='List of additional features with title and description'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='key_features',
            field=models.JSONField(default=list, help_text='List of key features with title, description, and image path'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='team_members',
            field=models.JSONField(default=list, help_text='List of team members with name, role, bio, and image path'),
        ),
        migrations.AddField(
            model_name='pagesettings',
            name='timeline_items',
            field=models.JSONField(default=list, help_text='List of timeline items with year and description'),
        ),
    ]
