# Generated by Django 5.2 on 2025-04-12 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Ongoing', 'Ongoing'), ('Stalled', 'Stalled'), ('Not Started', 'Not Started'), ('Under Procurement', 'Under Procurement')], default='Not Started', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('budget_allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funding_source', models.CharField(choices=[('County', 'County'), ('National', 'National Government'), ('Donors', 'Donors')], default='County', max_length=20)),
                ('contractor_name', models.CharField(blank=True, max_length=100)),
                ('implementing_agency', models.CharField(choices=[('County', 'County'), ('NGO', 'NGO'), ('Private', 'Private Sector')], default='County', max_length=20)),
                ('map_link', models.URLField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.department')),
                ('sub_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='project_photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='dashboard.subcounty')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.ward'),
        ),
    ]
