# Generated by Django 5.2 on 2025-04-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_project_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='No description available', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='financial_year',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementing_agency',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='remarks',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_of_funds',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dashboard.project')),
            ],
        ),
    ]
